language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install coveralls"

# command to run tests
script:
  python ./monopolpy.py
  #nosetests  --with-coverage --cover-package=ansi

after_success:
  coveralls